/**
 * B3c — the Messaging route cutover (§8.1, §18.1, §24.1, §25-B3c).
 *
 * Four claims, each with a way to fail:
 *
 *   copy    — every carried-forward StoreOp variant survives conversion
 *   verify  — replay equality is checked BEFORE anything is appended, and a
 *             mismatch blocks rather than records
 *   receipt — the receipt exists, counts what it did, and reconciles
 *   conflict— canonical + legacy with no receipt blocks boot and writes neither
 *
 * The legacy fixtures are hand-written in the OLD shape on purpose, including
 * the historic singleton `journal` that pre-dates §11.7. A fixture generated by
 * today's writer would prove nothing about migrating yesterday's file.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  checkMessagingStoreRoute, listMigratedOperations, normaliseLegacyOp,
  readLegacyStoreOp, readMessagingCutoverReceipt, runMessagingCutover,
} from "../adapters/cutover.js";
import { openFoundationMessagingStore } from "../adapters/store-foundation.js";
import { createSeededClock } from "../../adapters/clock-seeded.js";
import type { StoreOp } from "../../adapters/store-shared.js";

/** A legacy acceptance with the pre-§11.7 SINGLETON journal — the real shape. */
const LEGACY_ACCEPTANCE = {
  op: "acceptance",
  thread: {
    id: "thread_legacy1", kind: "thread", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", threadKind: "direct",
    direct: { pair: ["person_alice", "person_bob"] },
  },
  message: {
    id: "message_legacy1", kind: "message", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", threadId: "thread_legacy1",
    senderId: "person_alice", clientMessageId: "cmid-legacy-1", sequence: 1,
    priority: "normal", body: { text: "hello from the old store" },
  },
  snapshot: {
    id: "snapshot_legacy1", kind: "recipient-snapshot", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", messageId: "message_legacy1",
    recipients: ["person_bob"],
  },
  deliveries: [{
    id: "delivery_legacy1", kind: "delivery", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z",
    messageId: "message_legacy1", threadId: "thread_legacy1",
    recipientId: "person_bob", state: "pending",
  }],
  acceptance: {
    id: "acceptance_legacy1", kind: "acceptance", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", senderId: "person_alice",
    clientMessageId: "cmid-legacy-1", requestHash: "a".repeat(64),
    messageId: "message_legacy1", threadId: "thread_legacy1", sequence: 1,
    effectsPending: true,
  },
  // Singleton, not an array. This is what historic files actually contain.
  journal: {
    sequence: 1, kind: "MessageCommitted",
    message: {
      id: "message_legacy1", kind: "message", schemaVersion: 1,
      createdAt: "2026-01-01T00:00:00.000Z", threadId: "thread_legacy1",
      senderId: "person_alice", clientMessageId: "cmid-legacy-1", sequence: 1,
      priority: "normal", body: { text: "hello from the old store" },
    },
  },
};

const LEGACY_ROOM_THREAD = {
  op: "room-thread",
  thread: {
    id: "thread_legacyroom", kind: "thread", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", threadKind: "team",
    room: { authority: "team", externalId: "eng" },
  },
};

const LEGACY_DELIVERY_TRANSITION = {
  op: "delivery-transition",
  delivery: {
    id: "delivery_legacy1", kind: "delivery", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:01.000Z",
    messageId: "message_legacy1", threadId: "thread_legacy1",
    recipientId: "person_bob", state: "delivered",
  },
  journal: {
    sequence: 2, kind: "DeliveryUpdated",
    delivery: {
      id: "delivery_legacy1", kind: "delivery", schemaVersion: 1,
      createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:01.000Z",
      messageId: "message_legacy1", threadId: "thread_legacy1",
      recipientId: "person_bob", state: "delivered",
    },
  },
};

const LEGACY_SETTLED = { op: "settled", messageId: "message_legacy1" };

const LEGACY_POLICY = {
  op: "policy",
  dnd: {
    id: "dndpolicy_legacy1", kind: "dnd-policy", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", personId: "person_bob",
    enabled: true, revision: 1,
  },
  journal: {
    sequence: 3, kind: "PolicyChanged", personId: "person_bob",
    policy: "dnd", revision: 1,
  },
};

const LEGACY_TEMPLATE = {
  op: "template",
  template: {
    id: "template_legacy1", kind: "template", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:00.000Z", name: "standup",
    bindings: [], retired: false, revision: 1,
  },
  journal: {
    sequence: 4, kind: "TemplateWritten",
    template: {
      id: "template_legacy1", kind: "template", schemaVersion: 1,
      createdAt: "2026-01-01T00:00:00.000Z", name: "standup",
      bindings: [], retired: false, revision: 1,
    },
  },
};

const LEGACY_ATTEMPT = {
  op: "attempt",
  attempt: {
    id: "attempt_legacy1", kind: "delivery-attempt", schemaVersion: 1,
    createdAt: "2026-01-01T00:00:02.000Z", deliveryId: "delivery_legacy1",
    transport: "ws", outcome: "effect",
  },
};

/** All SEVEN carried-forward variants (§18.1 step 1). */
const ALL_VARIANTS = [
  LEGACY_ACCEPTANCE, LEGACY_ROOM_THREAD, LEGACY_DELIVERY_TRANSITION,
  LEGACY_ATTEMPT, LEGACY_POLICY, LEGACY_TEMPLATE, LEGACY_SETTLED,
];

interface Rig {
  readonly root: string;
  readonly dataRoot: string;
  readonly legacyStorePath: string;
}

function rig(lines: readonly unknown[]): Rig {
  const root = mkdtempSync(path.join(tmpdir(), "nvk-b3c-cutover-"));
  const legacyStorePath = path.join(root, "messaging-store.jsonl");
  writeFileSync(legacyStorePath, `${lines.map((line) => JSON.stringify(line)).join("\n")}\n`);
  return { root, dataRoot: path.join(root, "stores"), legacyStorePath };
}

test("every carried-forward StoreOp variant parses as legacy", () => {
  for (const [index, variant] of ALL_VARIANTS.entries()) {
    const parsed = readLegacyStoreOp(JSON.stringify(variant), index + 1);
    assert.equal(parsed.ok, true, `variant ${String(index)} was rejected`);
  }
});

test("a line carrying a B3c-only variant is refused as not-legacy", () => {
  // The B3c variants did not exist when that file was written, so a line
  // claiming one is corruption or smuggling. Either way it is not a legacy op.
  const parsed = readLegacyStoreOp(
    JSON.stringify({ op: "agent-endpoint-claim", claim: {} }), 1,
  );
  assert.equal(parsed.ok, false);
  if (parsed.ok) return;
  assert.equal(parsed.error.code, "ValidationFailed");
});

test("exactly two normalisations happen, and only on acceptance", () => {
  const acceptance = normaliseLegacyOp(LEGACY_ACCEPTANCE as unknown as StoreOp);
  assert.equal(acceptance.addedInboxItems, true);
  assert.equal(acceptance.wrappedJournal, true);
  const normalised = acceptance.operation as unknown as Record<string, unknown>;
  assert.equal(Array.isArray(normalised["journal"]), true);
  assert.deepEqual(normalised["agentInboxItems"], []);
  // Everything else is byte-identical to what arrived.
  assert.deepEqual(normalised["message"], LEGACY_ACCEPTANCE.message);
  assert.deepEqual(normalised["deliveries"], LEGACY_ACCEPTANCE.deliveries);
  assert.deepEqual(normalised["acceptance"], LEGACY_ACCEPTANCE.acceptance);

  for (const other of [LEGACY_ROOM_THREAD, LEGACY_POLICY, LEGACY_TEMPLATE, LEGACY_SETTLED]) {
    const untouched = normaliseLegacyOp(other as unknown as StoreOp);
    assert.equal(untouched.addedInboxItems, false);
    assert.equal(untouched.wrappedJournal, false);
    assert.deepEqual(untouched.operation, other);
  }
});

test("cutover migrates every line, writes a receipt, and leaves the source untouched", async () => {
  const harness = rig(ALL_VARIANTS);
  try {
    const before = readFileSync(harness.legacyStorePath, "utf8");
    const outcome = await runMessagingCutover(harness);
    assert.equal(outcome.ok, true);
    if (!outcome.ok || outcome.value.kind !== "completed") {
      assert.fail(`cutover did not complete: ${JSON.stringify(outcome)}`);
      return;
    }
    const { receipt } = outcome.value;
    assert.equal(receipt.sourceLineCount, ALL_VARIANTS.length);
    assert.equal(receipt.convertedCount, ALL_VARIANTS.length);
    assert.equal(receipt.normalisedInboxItems, 1);
    assert.equal(receipt.normalisedSingletonJournals, 1);
    assert.equal(receipt.replayEqual, true);
    assert.equal(receipt.traceComplete, true);

    const migrated = await listMigratedOperations(harness);
    assert.equal(migrated.ok, true);
    if (!migrated.ok) return;
    assert.equal(migrated.value.length, ALL_VARIANTS.length);
    assert.deepEqual(
      [...migrated.value].map((item) => item.storeSequence).sort((a, b) => a - b),
      [1, 2, 3, 4, 5, 6, 7],
    );

    // §27: provider and legacy originals are never written.
    assert.equal(readFileSync(harness.legacyStorePath, "utf8"), before);
  } finally {
    rmSync(harness.root, { recursive: true, force: true });
  }
});

test("the migrated journal replays into a working store", async () => {
  // The migration is only worth anything if what it wrote is READABLE by the
  // production adapter. Counting records proves the write; opening the store
  // proves the meaning survived.
  const harness = rig(ALL_VARIANTS);
  try {
    await runMessagingCutover(harness);
    const store = await openFoundationMessagingStore(
      createSeededClock({ seed: "after" }),
      { root: harness.root, dataRoot: harness.dataRoot },
    );
    const message = await store.getMessage("message_legacy1" as never);
    assert.equal(message.kind, "ok");
    if (message.kind !== "ok") return;
    assert.equal(message.value.body.text, "hello from the old store");

    const deliveries = await store.getDeliveries("message_legacy1" as never);
    assert.equal(deliveries.kind === "ok" && deliveries.value[0]?.state, "delivered");

    // §8.1: "B3-only endpoint/inbox variants start after the migrated maximum
    // storeSequence." A new operation must not reuse a migrated number.
    await store.commitAgentEndpointClaim({
      claim: {
        id: "agentEndpoint_new" as never, kind: "agentEndpointClaim", schemaVersion: 1,
        entityRevision: 1, createdAt: "2026-08-02T00:00:00.000Z",
        permissionLevel: "private", createdBy: "sys_agent_runtime",
        lastStoreOpId: "messagingStoreOp_x" as never,
        agentId: "agent_a" as never, agentRunId: "agentRun_1" as never,
        terminalSessionId: "terminal_1" as never,
        endpointGeneration: 0, state: "active",
      },
      expectedEndpointGeneration: -1,
    });
    await store.close();

    const migrated = await listMigratedOperations(harness);
    assert.equal(migrated.ok, true);
    if (!migrated.ok) return;
    const sequences = migrated.value.map((item) => item.storeSequence).sort((a, b) => a - b);
    assert.deepEqual(sequences, [1, 2, 3, 4, 5, 6, 7, 8],
      "a post-cutover operation reused a migrated sequence number");
  } finally {
    rmSync(harness.root, { recursive: true, force: true });
  }
});

test("a second cutover is a no-op that returns the original receipt", async () => {
  const harness = rig(ALL_VARIANTS);
  try {
    const first = await runMessagingCutover(harness);
    assert.equal(first.ok && first.value.kind, "completed");
    const second = await runMessagingCutover(harness);
    assert.equal(second.ok, true);
    if (!second.ok) return;
    assert.equal(second.value.kind, "already-done");

    const migrated = await listMigratedOperations(harness);
    assert.equal(migrated.ok && migrated.value.length, ALL_VARIANTS.length,
      "a repeated cutover migrated the same lines twice");
  } finally {
    rmSync(harness.root, { recursive: true, force: true });
  }
});

test("canonical and legacy with no receipt blocks boot, and writes neither", async () => {
  const harness = rig(ALL_VARIANTS);
  try {
    // A canonical journal already exists, with no cutover behind it.
    const store = await openFoundationMessagingStore(
      createSeededClock({ seed: "pre" }),
      { root: harness.root, dataRoot: harness.dataRoot },
    );
    await store.createDirectThread(["person_x" as never, "person_y" as never]);
    await store.close();

    const canonicalBefore = readFileSync(
      path.join(harness.dataRoot, "messagingStoreOps.jsonl"), "utf8",
    );
    const legacyBefore = readFileSync(harness.legacyStorePath, "utf8");

    const checked = await checkMessagingStoreRoute(harness);
    assert.equal(checked.ok, false);
    if (checked.ok) return;
    assert.equal(checked.error.code, "StoreRouteConflict");
    assert.equal(checked.error.details["legacyPath"], harness.legacyStorePath);

    assert.equal(
      readFileSync(path.join(harness.dataRoot, "messagingStoreOps.jsonl"), "utf8"),
      canonicalBefore,
    );
    assert.equal(readFileSync(harness.legacyStorePath, "utf8"), legacyBefore);
  } finally {
    rmSync(harness.root, { recursive: true, force: true });
  }
});

test("after a receipt exists the route is clear, conflict or not", async () => {
  const harness = rig(ALL_VARIANTS);
  try {
    assert.equal((await checkMessagingStoreRoute(harness)).ok, true);
    await runMessagingCutover(harness);
    const after = await checkMessagingStoreRoute(harness);
    assert.equal(after.ok, true);
    if (!after.ok) return;
    assert.equal(after.value, "clear");
    assert.notEqual(await readMessagingCutoverReceipt(harness), null);
  } finally {
    rmSync(harness.root, { recursive: true, force: true });
  }
});

test("a corrupt legacy line stops the whole cutover before anything is appended", async () => {
  const harness = rig([LEGACY_ACCEPTANCE, "{not json", LEGACY_SETTLED]);
  try {
    const outcome = await runMessagingCutover(harness);
    assert.equal(outcome.ok, false);
    if (outcome.ok) return;
    assert.equal(outcome.error.code, "ValidationFailed");
    // Nothing was written: the parse pass completes before the append pass
    // starts, so a bad line at position 2 never leaves position 1 half-migrated.
    const migrated = await listMigratedOperations(harness);
    assert.equal(migrated.ok && migrated.value.length, 0);
    assert.equal(await readMessagingCutoverReceipt(harness), null);
  } finally {
    rmSync(harness.root, { recursive: true, force: true });
  }
});

test("no legacy file means there is nothing to cut over", async () => {
  const root = mkdtempSync(path.join(tmpdir(), "nvk-b3c-nolegacy-"));
  try {
    const outcome = await runMessagingCutover({
      root, dataRoot: path.join(root, "stores"),
      legacyStorePath: path.join(root, "absent.jsonl"),
    });
    assert.equal(outcome.ok && outcome.value.kind, "not-required");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
